name = "gledo"
version = "1.0.0"
description = "Gleam decode Option"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "gledo" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
cleam = ">= 1.5.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
